name: rest-api

on:
  pull_request: 
    branches: [main, dev]

jobs:
  api-tests:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: mv schedule-data-service/database/template_nodehill_schedule.db schedule-data-service/database/nodehill_schedule.db
    - run: ls schedule-data-service/database/
    - run: cd admin/ && npm ci && npm run build
    - run: cd schedule-data-service/ && npm ci
    - run: npm install -g pm2
    - run: pm2 start "npm run dev"
    - run: npm install -g newman
    - run: newman run test-api-postman/admin-tests.postman_collection.json
    - run: newman run test-api-postman/user-tests.postman_collection.json
    - run: newman run test-api-postman/visitor-test.postman_collection.json
